name: Build/release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: git checkout master
        uses: actions/checkout@v2

      - name: install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: install dependencies
        run: npm ci

      - name: lint code
        run: npm run lint

      - name: build and release
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}